apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: athul9thd/spring-petclinic-api-gateway:dev
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: api-gateway
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka"
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
