apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: athul9thd/spring-petclinic-vets-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: vets-service

            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka"

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
