apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: athul9thd/spring-petclinic-config-server:dev
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/athulraj9thd/petclinic-config-repo
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: main
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
